language: python

python:
  # - "2.7"
  - "3.6"

# services:

#  - mysql

env:
  -DJANGO=1.8 DB=sqlite
  
#install:
#  - pip install -r requirements.txt

#before_script:
  - mysql -e 'create database test;' -u root
  
script:
  - python manage.py test